# =============================================
# PostgreSQL - Supabase
# =============================================
spring.datasource.url=jdbc:postgresql://db.xdbwlucidbcjntyyuppp.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Coliseu50@@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =============================================
# MongoDB
# =============================================
spring.data.mongodb.uri=mongodb+srv://gustavoimundo12345_db_user:senha123456@cluster0.8epfkgg.mongodb.net/ifei_delivery?retryWrites=true&w=majority
# =============================================
# Cassandra - Astra DB (DATABASE2)
# =============================================

spring.cassandra.keyspace-name=ifei

astra.db.client-id=gukGLqcBnMqOzUcqzYfSdoKL
astra.db.client-secret=kk8eLdtqtQ_XheZLzG_useor7SU0LsyT47ZtWCGh2noU_Gd2cImByGaUh5g3SZrGGsyTZIcFlc_4SGXQQZFaU0q2DnhfU6eZq21UDcfrI0-9ExHjA9BB5U0Jm5lCIp8
astra.db.token=AstraCS:gukGLqcBnMqOzUcqzYfSdoKL:7ba94c3fec22499d0671f5c2e427cc85fab2b4e976542b0f77c906de10c1ba93
# =============================================
# Servidor
# =============================================
server.port=8080
